# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  timeout1s:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a file
        run: |
          export dr=/home/giulio/runner_results/`printf '%(%Y-%m-%d-%H-%M-%S)T\n' -1 `_$GITHUB_SHA
          mkdir -p $dr
          cd VeriSmart
          for c in hello_world/test.c
          do
            mkdir -p $dr/$c/logs
            ./verismart.py -i /home/giulio/benchmarks/$c --debug --stop-on-fail -T 10 &> $dr/$c/output.txt
            mv logs/* $dr/$c/logs
          done
