format_version: '1.0'

# old file name: char_pc8736x_gpio_pc8736x_gpio_configure_pc8736x_gpio_current_true-unreach-call.i
input_files: 'char_pc8736x_gpio_pc8736x_gpio_configure_pc8736x_gpio_current.i'

properties:
  - property_file: ../properties/unreach-call.prp
    expected_verdict: true
